[tools]
gradle = "8"
java = "21"

[env]
"BIND_UPDATE_KEY" = { value = "dGhpcy1pc19qdXN0LXRlc3Qtc2VjcmV0LXN0cmluZw==", redact = true }

[tasks.build-docker]
description = "Build the docker image"
run = "docker build . -t theyoxy/sml:develop"
