ktor:
  deployment:
    path: ${KTOR_DEPLOYMENT_PATH:.}
    port: 8080
  application:
    modules:
      - be.endevops.ApplicationKt.module

dbfile: ${DB_FILE:./data/database.db}
dns:
  server: ${DNS_SERVER:127.0.0.1}
  port: ${DNS_PORT:53}
  keyname: ${DNS_KEY_NAME:default}
  keysecret: ${DNS_KEY_SECRET:default}

