ktor:
  deployment:
    path: ${KTOR_DEPLOYMENT_PATH:.}
    port: 8080
  application:
    modules:
      - be.endevops.ApplicationKt.module

dbfile: ${SML_DB_FILE:./data/database.db}
dns:
  server: ${SML_DNS_SERVER:127.0.0.1}
  port: ${SML_DNS_PORT:53}
  zone: ${SML_DNS_ZONE:europa.eu}
  domain: ${SML_DNS_DOMAIN:acc.edelivery.tech.ec.europa.eu}
  keyname: ${SML_DNS_KEY_NAME:default}
  keysecret: ${SML_DNS_KEY_SECRET:default}
